version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongo"
    ports:
      - 27017:27017
  app:
    build: .
    image: snakeeyes
    ports:
      - 8080:8080
    links:
      - mongodb